project:
  type: website
  output-dir: docs

website:
  title: "personal_website_and_portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - case_study.qmd
      - resume.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

