---
title: "Case Study on Portland, OR"
---

In this section you can see the culmination of all that I have learned in this class. I perform a case study on demographic change in Multnomah county, where I grew up. There are this many people in multnomah county

```{r}
#| echo: false
library(tidycensus)
library(tidyverse)
library(readr)
library(ggplot2)
library(scales)
census_api_key("e9fab01c12797a522e0541e2b24496af231563af", overwrite = TRUE, install = TRUE)
readRenviron("~/.Renviron")

multnomah_pep_2016 <- get_estimates(
  geography = "county",
  state = "OR",
  county = "Multnomah",
  product = "characteristics",
  breakdown = c("SEX", "AGEGROUP"),
  breakdown_labels = TRUE,
  year = 2016
)

multnomah_pep_filtered <- multnomah_pep_2016 %>%
  filter(str_detect(AGEGROUP, "^Age"),
         SEX != "Both sexes") %>%
  mutate(value = ifelse(SEX == "Male", -value, value))

multnomah_pyramid <- ggplot(multnomah_pep_filtered,
                           aes(x = value,
                               y = AGEGROUP,
                               fill = SEX)) +
  geom_col(width = 0.95, alpha = 0.75) +
  theme_minimal(base_family = "Verdana", base_size = 12) +
  scale_x_continuous(
    labels = ~ number_format(scale = .001, suffix = "k")(abs(.x)),
    limits = 45000 * c(-1,1)
  ) +
  scale_y_discrete(labels = ~ str_remove_all(.x, "Age\\s|\\syears")) +
  scale_fill_manual(values = c("deeppink", "deepskyblue")) +
  labs(x = "",
       y = "2016 Census Bureau\n Population Estimate",
       title = "Population structure in Multnomah County, OR",
       fill = "",
       caption = "Sources: US Census Bureau PEP, tidycensus R package") +
  theme_minimal(base_family = "Verdana", base_size = 12) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", margin = margin(b = 15)),
    axis.title.y = element_text(margin = margin(r = 25, l = 10), vjust = 0.5),
    plot.margin = margin(t = 20, r = 25, b = 20, l = 25, unit = "pt")
  )

multnomah_pyramid
```

```{r}
#| echo: false
# libraries:
library(tidycensus)
library(tidyverse)
library(tigris)
library(ggplot2)
library(sf)
library(crsuggest)
library(mapview)
library(mapboxapi)
library(spdep)

census_api_key("e9fab01c12797a522e0541e2b24496af231563af", overwrite = TRUE, install = TRUE)
readRenviron("~/.Renviron")
options(tigris_use_cache = TRUE)


or <- get_acs(
  geography = "tract",
  variables = "B19013_001",
  state = "OR",
  county = "Multnomah",
  geometry = TRUE,
  year = 2020,
  cb = FALSE
) %>%
  st_transform(8316)

#or_crs <- suggest_crs(or)
#or_crs

or_erase <- erase_water(or, area_threshold = 0.8)

or_water_erase <- ggplot(or_erase) +
  geom_sf(aes(fill = estimate)) +
  scale_fill_viridis_c(labels = scales::label_dollar()) +
  theme_void() +
  labs(fill = "Median household\nincome",
       title = "Median Household Income by Census tract, Multnomah County",
       caption = "Data source: 2016-2020 ACS via the tidycensus R package.")

or_water_erase
```

```{r}
#| echo: false
# Libraries
library(tidycensus)
library(tidyverse)
library(segregation)
library(tigris)
library(sf)
library(dplyr)
library(ggplot2)

options(tigris_use_cache = TRUE)

multnomah_acs_data <- get_acs(
  geography = "tract",
  variables = c(
    white = "B03002_003",
    black = "B03002_004",
    asian = "B03002_006",
    hispanic = "B03002_012"
  ),
  state = "OR",
  county = "Multnomah",
  geometry = FALSE, # Dropping geometry here for speed; we'll join it back later
  year = 2016
)

multnomah_acs_data %>%
  filter(variable %in% c("white", "hispanic")) %>%
  dissimilarity(
    group = "variable",
    unit = "GEOID",
    weight = "estimate"
  )

multnomah_mutual <- mutual_total(
  data = multnomah_acs_data,
  group = "variable",
  unit = "GEOID",
  weight = "estimate"
)
print(multnomah_mutual)

multnomah_local_seg <- multnomah_acs_data %>%
  mutual_local(
    group = "variable",
    unit = "GEOID",
    weight = "estimate",
    wide = TRUE
  )


multnomah_tracts <- tracts("OR", county = "Multnomah", cb = TRUE, year = 2016)

multnomah_tracts_seg <- multnomah_tracts %>%
  inner_join(multnomah_local_seg, by = "GEOID")

multnomah_tracts_seg_plot <- multnomah_tracts_seg %>%
  ggplot(aes(fill = ls)) +
  geom_sf(color = "white", size = 0.05) + 
  coord_sf(crs = 2992) + # Updated CRS specific to Northern Oregon / Portland
  scale_fill_distiller(palette = "YlGnBu", direction = 1) +
  theme_void() +
  labs(
    fill = "Local Segregation\nIndex (ls)",
    title = "Local Segregation Index by Census Tract",
    subtitle = "Multnomah County, OR (2016 ACS)",
    caption = "Sources: US Census Bureau, segregation R package"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )

multnomah_tracts_seg_plot
```
